### PR TITLE
compilation works with v0.13.0-dev.130+98a30acad

### PR DESCRIPTION
**Pull request by veggiemonk**
tested https://github.com/kristoff-it/zine-ssg.io

with:

```zig
.dependencies = .{
    .zine = .{
        .url = "git+https://github.com/veggiemonk/zine#1de396698c2f336371668d18c87fee1d32c98e05",
        .hash = "1220b10ab22d344339c4178565f981e7273d38ee702fbf9b18c1ae67da5eea81f34d",
    },
},
```

### CODE REVIEW

**Comment by MFAshby** [comment]
You beat me to it, thanks :D 

I would suggest getting the various upstream PRs merged first if possible to avoid depending on my forks of things, otherwise a follow-up once each is merged to revert the dependency to the canonical repo.

**Comment by veggiemonk** [comment]
@MFAshby I was just telling others on Discord that I based my work on what you did, so thank you 🙏 
@kristoff-it said he will be working on it soon. Others asked for a working version as it didn't compiled either on 0.12 or master, so I just shared mine to unlock them while waiting for upstream.

**Comment by MFAshby** [comment]
No problem, thank you. FYI tested this branch and it builds my site just fine.

**Comment by MFAshby** [comment]
latest zig has another error when I try to run `zig build serve`, looks like some stdlib change to rename std.ChildProcess -> std.process.Child
```
diff --git a/zine/server/Reloader.zig b/zine/server/Reloader.zig
index ab661ad..38fcc55 100644
--- a/zine/server/Reloader.zig
+++ b/zine/server/Reloader.zig
@@ -46,7 +46,7 @@ pub fn onInputChange(self: *Reloader, path: []const u8, name: []const u8) void {
     _ = name;
     _ = path;
     log.debug("re-building!", .{});
-    const result = std.ChildProcess.run(.{
+    const result = std.process.Child.run(.{
         .allocator = self.gpa,
         .argv = &.{ self.zig_exe, "build" },
     }) catch |err| {
```

**Comment by kristoff-it** [comment]
Thank you all for your interest & this PR. I'm starting the process to stick to tagged versions of Zig so now I'm targeting 0.12. AFAIK it shouldn't take long for 0.13 to come out so once that happens I will revisit this PR. 

Hopefully this doesn't disrupt your workflow too much :^)

**Comment by MFAshby** [comment]
That really didn't take long at all 🏃 0.13 has been cut now. I'll try test it later today. 

https://ziglang.org/download/0.13.0/release-notes.html

**Pull request merged**
