### PR TITLE
Render footnotes

### PR DESCRIPTION
**Pull request by brandondyck**
We can't render footnote definitions by calling `cmark_render_html` on each node separately, because that function relies upon counting footnotes definitions as it writes them. Instead, I mostly duplicated cmark-gfm's rendering logic; the only (intentional) differences are that I did not escape `href` attributes in footnote links (though this should probably be done eventually), and I didn't bother putting in all the whitespace around elements that cmark-gfm does.

This depends upon kristoff-it/supermd#9, and build.zig.zon will need to be updated once that is merged.

### CODE REVIEW

**Comment by kristoff-it** [comment]
Thank you for your PR(s). I've merged all the prerequisites to land footnote support in Zine, but for this last integration step I want to move in a different direction compared to what this PR does.

More specifically, direct integration forces the renderer to make too many decisions about how the HTML should look like. We should strive to minimize the amount of hardcoded IDs, classes and data attributes we generate.

I've put my design idea and suggestions in https://github.com/kristoff-it/zine/issues/92.

Feel free to update this PR towards that design or to start a new one as you see fit. If you do open a new PR, please close this one first.

If you decide to continue working on this, I'm happy to answer questions in both the aforementioned Issue and Discord as well.

**Comment by brandondyck** [comment]
I haven't tested docgen yet, but rendering works.

**Comment by brandondyck** [comment]
Docgen is working correctly now. I compared the output with the original, and the only differences are the additions of `Page.footnotes?` and the `Footnote` type.

**Comment by brandondyck** [comment]
Fixed for real. This time I checked the docgen output and tested the `footnotes?` example code on pages with and without footnotes.

**Comment by kristoff-it** [comment]
Thank you!

**Pull request merged**
